# Generated by Django 5.0.8 on 2024-08-12 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0002_remove_book_publisher_date_book_publication_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="genre",
            field=models.CharField(default=1, max_length=100, verbose_name="장르"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="book",
            name="summary",
            field=models.TextField(default=1, verbose_name="요약"),
            preserve_default=False,
        ),
    ]
