# Generated by Django 5.1 on 2024-08-23 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_user_post_like_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="likes_count",
            field=models.IntegerField(default=0),
        ),
    ]
